//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCK_Off_Fac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Site
    {
        public int Site_ID { get; set; }
        public string Site_Code { get; set; }
        public string Site_Name { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public Nullable<int> Post_Code { get; set; }
        public string County { get; set; }
    }
}
