//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCK_Off_Fac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Category
    {
        public int ID { get; set; }
        public string Cat_Name { get; set; }
        public string Cat_Des { get; set; }
        public string Status { get; set; }
    }
}
