//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCK_Off_Fac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCK_Off_FacEntities : DbContext
    {
        public TCK_Off_FacEntities()
            : base("name=TCK_Off_FacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master_Category> Master_Category { get; set; }
        public virtual DbSet<Master_Item> Master_Item { get; set; }
        public virtual DbSet<Master_Location> Master_Location { get; set; }
        public virtual DbSet<Master_Member> Master_Member { get; set; }
        public virtual DbSet<Master_Site> Master_Site { get; set; }
        public virtual DbSet<Master_Type> Master_Type { get; set; }
        public virtual DbSet<TR_Request> TR_Request { get; set; }
        public virtual DbSet<TR_Reserve> TR_Reserve { get; set; }
        public virtual DbSet<TR_Warehouse> TR_Warehouse { get; set; }
    }
}
