//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCK_Off_Fac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Warehouse
    {
        public int ID { get; set; }
        public string Prefix { get; set; }
        public string Bracode { get; set; }
        public Nullable<System.DateTime> WH_Create { get; set; }
        public Nullable<System.DateTime> WH_Update { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> Sum_Qty { get; set; }
        public string WH_User { get; set; }
        public Nullable<int> Use { get; set; }
        public Nullable<int> Plan { get; set; }
        public Nullable<int> Reserve { get; set; }
        public Nullable<int> PD { get; set; }
        public string Starus { get; set; }
    }
}
